### ISSUE TITLE
Hide sensitive information

### ISSUE THREAD

**Issue by yuweipei** [timtianyang/group-reminder#1]
@timtianyang Is there any way we can hide those sensitive information, such as spreadsheet ID or your phone number?

**Comment by timtianyang** [comment]
From whom? The script itself is saved on your google drive privately.

**Comment by timtianyang** [comment]
admin_phone is a default value and you can set it to anyone in case there is an error. It will be overwritten when it reads from the sheet. The sheetID however, could be received from a Get request as payload. That way the trigger and the code is separate if you so desire.
